In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import pandas as pd 
import numpy as np 
import pickle 

# Define Model

In [2]:
class lstm_Classifier(nn.Module):
    def __init__ (self, input_size, hidden_size, num_layers, batch_size, dropout, num_classes):
        super(lstm_Classifier, self).__init__()

        self.input_size = input_size
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.batch_size = batch_size
        self.dropout = dropout
        self.num_classes = num_classes

        self.lstm = nn.LSTM(input_size = input_size, hidden_size = hidden_size, 
                            num_layers = num_layers, dropout= dropout)
        self.fc = nn.Linear(hidden_size,num_classes)

    def init_hidden(self):
        hidden = (torch.randn(self.num_layers, self.batch_size, self.hidden_size),
                  torch.randn(self.num_layers, self.batch_size, self.hidden_size))
        return hidden

    def forward(self, X, hidden = None): 
        
        if hidden == None: 
            hidden = self.init_hidden()

        X,_ = self.lstm(X, hidden)
        X = self.fc(X[-1])

        return X

In [7]:
input_size = 4
num_layers = 5
hidden_size = 4
batch_size = 6
lstm = nn.LSTM(input_size = input_size, hidden_size = hidden_size, num_layers = num_layers, dropout= .05) # input = [Open, HIgh, low, Close] output = [Up, Neutral, Down]

In [8]:
model = lstm_Classifier(input_size = input_size, hidden_size = hidden_size,
                                 num_layers = num_layers,batch_size=batch_size, dropout= .05, num_classes=3)

In [10]:

sequence_len = 2
inputs = [torch.randn(sequence_len, batch_size, input_size) for _ in range(10)]

# initialize the hidden state.
hidden = (torch.randn(num_layers, batch_size, hidden_size),
          torch.randn(num_layers, batch_size, hidden_size)) 

for i in inputs:
    # Step through the sequence one element at a time.
    # after each step, hidden contains the hidden state.
    
    # out, hidden = lstm(i.view(sequence_len, batch_size, input_size), hidden)
    # out, hidden = lstm(i, hidden)
    # out, hidden = lstm(i)
    # print(out)
    
    out = model(i)

    print(out)
    # print(hidden)

tensor([[ 0.5911, -0.3727,  0.1231],
        [ 0.5050, -0.3263,  0.3073],
        [ 0.6452, -0.3181,  0.1679],
        [ 0.4925, -0.2197,  0.4348],
        [ 0.4745, -0.2501,  0.2997],
        [ 0.5789, -0.1922,  0.3918]], grad_fn=<AddmmBackward>)
tensor([[ 0.4094, -0.1620,  0.4220],
        [ 0.5720, -0.2716,  0.4027],
        [ 0.5855, -0.2524,  0.3196],
        [ 0.5784, -0.2685,  0.3520],
        [ 0.5232, -0.4130,  0.4154],
        [ 0.5466, -0.2249,  0.2849]], grad_fn=<AddmmBackward>)
tensor([[ 0.5158, -0.3795,  0.2884],
        [ 0.5375, -0.2310,  0.2456],
        [ 0.5348, -0.2312,  0.4341],
        [ 0.6264, -0.3255,  0.3834],
        [ 0.4702, -0.2733,  0.3413],
        [ 0.5794, -0.2520,  0.3490]], grad_fn=<AddmmBackward>)
tensor([[ 0.5699, -0.2891,  0.2860],
        [ 0.6285, -0.3316,  0.3064],
        [ 0.5425, -0.2984,  0.3166],
        [ 0.5620, -0.3181,  0.3408],
        [ 0.5635, -0.2483,  0.2991],
        [ 0.5292, -0.2923,  0.1905]], grad_fn=<AddmmBackward>)
tensor([

In [6]:
print(out[-1])

tensor([-0.1538, -0.5690,  0.3186], grad_fn=<SelectBackward>)
